# Generated by Django 3.2.12 on 2022-03-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code_gender', models.CharField(choices=[('F', 'F'), ('M', 'M')], max_length=1)),
                ('flag_own_car', models.BooleanField(default=False)),
                ('flag_own_realty', models.BooleanField(default=False)),
                ('cnt_children', models.IntegerField(default=0)),
                ('amt_income_total', models.FloatField(default=0)),
                ('name_income_type', models.CharField(choices=[('commercial', 'Commercial associate'), ('working', 'Working'), ('pensioner', 'Pensioner'), ('state', 'State servant'), ('student', 'Student')], default='working', max_length=20)),
                ('name_education_type', models.CharField(choices=[('degree', 'Academic degree'), ('higher', 'Higher education'), ('secondary', 'Secondary / secondary special'), ('higher_incomplete', 'Incomplete higher'), ('lower', 'Lower secondary')], default='secondary', max_length=30)),
                ('name_family_status', models.CharField(choices=[('civil', 'Civil marriage'), ('married', 'Married'), ('single', 'Single / not married'), ('separated', 'Separated'), ('widow', 'Widow')], default='single', max_length=20)),
                ('name_housing_type', models.CharField(choices=[('rented', 'Rented apartment'), ('house', 'House / apartment'), ('coop', 'Co-op apartment'), ('municipal', 'Municipal apartment'), ('office', 'Office apartment'), ('parents', 'With parents')], default='rented', max_length=20)),
                ('days_birth', models.IntegerField(default=0)),
                ('days_employed', models.IntegerField(default=0)),
                ('flag_mobil', models.BooleanField(default=False)),
                ('flag_work_phone', models.BooleanField(default=False)),
                ('flag_phone', models.BooleanField(default=False)),
                ('flag_email', models.BooleanField(default=False)),
                ('occupation_type', models.CharField(max_length=30)),
                ('cnt_fam_members', models.IntegerField(default=0)),
                ('status', models.BooleanField(null=True)),
            ],
        ),
    ]
