version: '3.7'

services:

  mysql:
    container_name: mysql
    restart: always
    image: mysql:latest
    environment:
      - MYSQL_PORT=3306  # cannot change this port to other number
      - MYSQL_DATABASE=creditrisk
      - MYSQL_USER=mark
      - MYSQL_PASSWORD=superpassw
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - "3306:3306"

  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - './frontend/:/app' # ? maybe like that try it later
      - '/app/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start

  backend:
    container_name: backend
    build: ./backend
    command: sh -c "cd backend/ &&
                gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mysql
